image: Visual Studio 2017
platform: x64
skip_non_tags: true

install:
  - git submodule update --init --recursive
  - git clone -b master https://github.com/flutter/flutter.git %APPVEYOR_BUILD_FOLDER%\..\flutter

build_script:
  - set "PATH=%APPVEYOR_BUILD_FOLDER%\..\flutter\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\;%PATH%"
  - set "ENABLE_FLUTTER_DESKTOP=true"
  - ps: cd "$env:APPVEYOR_BUILD_FOLDER\cruzall"
  - ps: Copy-Item "..\cruzall-desktop\example\windows" -Destination "$env:APPVEYOR_BUILD_FOLDER\cruzall\windows" -Recurse
  - ps: Copy-Item "desktop\pubspec.*" -Destination "$env:APPVEYOR_BUILD_FOLDER\cruzall" -force
  - flutter packages get
  - flutter build -v windows --release
  - ps: cd ..
  - makensis installer.nsi

on_success:
  - echo Success
  - dir Cruzall-x64-installer.exe
  - CertUtil -hashfile Cruzall-x64-installer.exe md5

on_failure:
  - echo Failure

deploy:
  release: Cruzall-v$(appveyor_build_version)
  description: 'Cruzall: HD cruzbit wallet'
  provider: GitHub
  auth_token:
    secure: v63vqyGOnTzYRb+8OaYranlVePalCI8/8WTg2jbnY/TJci2wrTa0nmbj7nK31ZQv
  artifact: Cruzall-x64-installer.exe
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
